## Setup

This notebook covers the Pandas tools that are most useful when preparing and exploring data for machine learning.

Pandas is mainly used for working with **structured data** such as tables and CSV files.

In [1]:
import numpy as np
import pandas as pd

## Series and DataFrames

### Series

A Series is a one-dimensional labeled data structure.

A single column of a dataset is usually represented as a Series.

In [2]:
scores = pd.Series([65, 82, 58, 91, 85])

scores

0    65
1    82
2    58
3    91
4    85
dtype: int64

### DataFrame

A `DataFrame` is a two-dimensional table with rows and columns.

For an ML dataset:

- rows usually represent **samples**
- columns usually represent **features**
- one column may represent the **target**

In [3]:
data = {
    "age": [20, 21, 19, 22, 20, 23, 21, 19, 24, 22,
            20, 25, 21, 23, 19, 22, 24, 20, 21, 23],

    "hours_studied": [3, 5, 2, 7, 6, 8, 4, 2, 9, 6,
                      3, 10, 5, 7, 1, 6, 8, 4, 5, 7],

    "attendance": [70, 85, 65, 95, 90, 98, 78, 60, 92, 88,
                   72, 96, 84, 91, 55, 87, 94, 76, 82, 89],

    "score": [65, 82, 58, 91, 85, 96, 73, 52, 94, 87,
              68, 98, 80, 90, 45, 84, 92, 70, 79, 88]
}

df = pd.DataFrame(data)

df

    age  hours_studied  attendance  score
0    20              3          70     65
1    21              5          85     82
2    19              2          65     58
3    22              7          95     91
4    20              6          90     85
5    23              8          98     96
6    21              4          78     73
7    19              2          60     52
8    24              9          92     94
9    22              6          88     87
10   20              3          72     68
11   25             10          96     98
12   21              5          84     80
13   23              7          91     90
14   19              1          55     45
15   22              6          87     84
16   24              8          94     92
17   20              4          76     70
18   21              5          82     79
19   23              7          89     88

## Loading a Dataset

Pandas provides functions for reading data from different file formats. In ML, CSV files are especially common, but you may also encounter Excel and plain text files.

General syntax:

```python
df = pd.read_csv("data.csv")
df = pd.read_excel("data.xlsx")
```
For a text file, the appropriate function depends on how the data is structured.

if values are separated by spaces:
```python
df = pd.read_csv("data.txt", sep=" ")
```

If values are separated by tabs:
```python
df = pd.read_csv("data.txt", sep="\t")
```

If values are separated by commas:
```python
df = pd.read_csv("data.txt", sep=",")
```

The result is a Pandas DataFrame.

## Inspecting a Dataset

Before training a model, we usually inspect the dataset to understand its size, columns, data types, and basic statistics.

### head and tail 

head: shows the first rows

tail: shows the last rows

In [4]:
df.head()

   age  hours_studied  attendance  score
0   20              3          70     65
1   21              5          85     82
2   19              2          65     58
3   22              7          95     91
4   20              6          90     85

In [5]:
df.tail()

    age  hours_studied  attendance  score
15   22              6          87     84
16   24              8          94     92
17   20              4          76     70
18   21              5          82     79
19   23              7          89     88

### shape, columns, and dtypes

shape: number of rows, number of columns

columns: column names

dtypes: data type of each column

In [6]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)

print("\nData types:")
print(df.dtypes)

Shape: (20, 4)

Columns:
Index(['age', 'hours_studied', 'attendance', 'score'], dtype='object')

Data types:
age              int64
hours_studied    int64
attendance       int64
score            int64
dtype: object

### info and describe

info: a general overview of the DataFrame including
- Number of rows
- Number of columns
- Column names
- Number of non-null values
- Data type of each column
- Approximate memory usage

describe: gives descriptive statistics for numerical columns

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            20 non-null     int64
 1   hours_studied  20 non-null     int64
 2   attendance     20 non-null     int64
 3   score          20 non-null     int64
dtypes: int64(4)
memory usage: 768.0 bytes

In [8]:
df.describe()

            age  hours_studied  attendance      score
count  20.00000      20.000000    20.00000  20.000000
mean   21.45000       5.400000    82.35000  78.850000
std     1.79106       2.458069    12.41508  15.016745
min    19.00000       1.000000    55.00000  45.000000
25%    20.00000       3.750000    75.00000  69.500000
50%    21.00000       5.500000    86.00000  83.000000
75%    23.00000       7.000000    91.25000  90.250000
max    25.00000      10.000000    98.00000  98.000000

## Indexing and Selection

### Selecting One Column

In [9]:
df["hours_studied"]

0      3
1      5
2      2
3      7
4      6
5      8
6      4
7      2
8      9
9      6
10     3
11    10
12     5
13     7
14     1
15     6
16     8
17     4
18     5
19     7
Name: hours_studied, dtype: int64

Selecting one column with one pair of brackets returns a Series.

### Selecting Multiple Columns

In [10]:
df[["hours_studied", "attendance", "score"]]

    hours_studied  attendance  score
0               3          70     65
1               5          85     82
2               2          65     58
3               7          95     91
4               6          90     85
5               8          98     96
6               4          78     73
7               2          60     52
8               9          92     94
9               6          88     87
10              3          72     68
11             10          96     98
12              5          84     80
13              7          91     90
14              1          55     45
15              6          87     84
16              8          94     92
17              4          76     70
18              5          82     79
19              7          89     88

Selecting multiple columns requires a list of column names.

This returns a DataFrame.

### iloc

iloc selects data using integer positions.

General syntax:

```python
df.iloc[rows, columns]
```

In [11]:
# First row
df.iloc[0]

age              20
hours_studied     3
attendance       70
score            65
Name: 0, dtype: int64

In [12]:
# First three rows
df.iloc[:3]

   age  hours_studied  attendance  score
0   20              3          70     65
1   21              5          85     82
2   19              2          65     58

In [13]:
# First three rows and first two columns
df.iloc[:3, :2]

   age  hours_studied
0   20              3
1   21              5
2   19              2

### loc

loc selects data using labels or Boolean conditions.

In [14]:
# Rows where age is 20:
df.loc[df["age"] == 20]

    age  hours_studied  attendance  score
0    20              3          70     65
4    20              6          90     85
10   20              3          72     68
17   20              4          76     70

In [15]:
df.loc[:, ["hours_studied", "score"]]

    hours_studied  score
0               3     65
1               5     82
2               2     58
3               7     91
4               6     85
5               8     96
6               4     73
7               2     52
8               9     94
9               6     87
10              3     68
11             10     98
12              5     80
13              7     90
14              1     45
15              6     84
16              8     92
17              4     70
18              5     79
19              7     88

### Filtering Rows

In [16]:
df[df["score"] >= 80]

    age  hours_studied  attendance  score
1    21              5          85     82
3    22              7          95     91
4    20              6          90     85
5    23              8          98     96
8    24              9          92     94
9    22              6          88     87
11   25             10          96     98
12   21              5          84     80
13   23              7          91     90
15   22              6          87     84
16   24              8          94     92
19   23              7          89     88

Multiple conditions can be combined with:

- `&` for AND
- `|` for OR

Each condition should be inside parentheses.

In [17]:
df[
    (df["hours_studied"] >= 5) &
    (df["score"] >= 80)
]

    age  hours_studied  attendance  score
1    21              5          85     82
3    22              7          95     91
4    20              6          90     85
5    23              8          98     96
8    24              9          92     94
9    22              6          88     87
11   25             10          96     98
12   21              5          84     80
13   23              7          91     90
15   22              6          87     84
16   24              8          94     92
19   23              7          89     88

## Working with Missing Values

Real datasets often contain missing values.

Pandas represents many missing numerical values as `NaN`.

In [18]:
df_missing = pd.DataFrame({
    "hours_studied": [3, 5, np.nan, 7, 6],
    "attendance": [70, 85, 65, np.nan, 90],
    "score": [65, 82, 58, 91, 85]
})

df_missing

   hours_studied  attendance  score
0            3.0        70.0     65
1            5.0        85.0     82
2            NaN        65.0     58
3            7.0         NaN     91
4            6.0        90.0     85

### Detecting Missing Values

In [19]:
df_missing.isna()

   hours_studied  attendance  score
0          False       False  False
1          False       False  False
2           True       False  False
3          False        True  False
4          False       False  False

In [20]:
df_missing.isna().sum()

hours_studied    1
attendance       1
score            0
dtype: int64

### Removing Missing Values

In [21]:
df_missing.dropna()

   hours_studied  attendance  score
0            3.0        70.0     65
1            5.0        85.0     82
4            6.0        90.0     85

### Filling Missing Values

In [22]:
df_missing.fillna(0)

   hours_studied  attendance  score
0            3.0        70.0     65
1            5.0        85.0     82
2            0.0        65.0     58
3            7.0         0.0     91
4            6.0        90.0     85

## Basic Column Operations

Pandas can perform vectorized calculations on complete columns.

In [23]:
df["score_fraction"] = df["score"] / 100

df

    age  hours_studied  attendance  score  score_fraction
0    20              3          70     65            0.65
1    21              5          85     82            0.82
2    19              2          65     58            0.58
3    22              7          95     91            0.91
4    20              6          90     85            0.85
5    23              8          98     96            0.96
6    21              4          78     73            0.73
7    19              2          60     52            0.52
8    24              9          92     94            0.94
9    22              6          88     87            0.87
10   20              3          72     68            0.68
11   25             10          96     98            0.98
12   21              5          84     80            0.80
13   23              7          91     90            0.90
14   19              1          55     45            0.45
15   22              6          87     84            0.84
16   24              8          94     92            0.92
17   20              4          76     70            0.70
18   21              5          82     79            0.79
19   23              7          89     88            0.88

We can also create Boolean columns from conditions.

In [24]:
df["passed"] = df["score"] >= 60

df

    age  hours_studied  attendance  score  score_fraction  passed
0    20              3          70     65            0.65    True
1    21              5          85     82            0.82    True
2    19              2          65     58            0.58   False
3    22              7          95     91            0.91    True
4    20              6          90     85            0.85    True
5    23              8          98     96            0.96    True
6    21              4          78     73            0.73    True
7    19              2          60     52            0.52   False
8    24              9          92     94            0.94    True
9    22              6          88     87            0.87    True
10   20              3          72     68            0.68    True
11   25             10          96     98            0.98    True
12   21              5          84     80            0.80    True
13   23              7          91     90            0.90    True
14   19              1          55     45            0.45   False
15   22              6          87     84            0.84    True
16   24              8          94     92            0.92    True
17   20              4          76     70            0.70    True
18   21              5          82     79            0.79    True
19   23              7          89     88            0.88    True

If a temporary column is no longer needed, drop() can remove it.

In [25]:
df = df.drop(columns=["score_fraction"])

df

    age  hours_studied  attendance  score  passed
0    20              3          70     65    True
1    21              5          85     82    True
2    19              2          65     58   False
3    22              7          95     91    True
4    20              6          90     85    True
5    23              8          98     96    True
6    21              4          78     73    True
7    19              2          60     52   False
8    24              9          92     94    True
9    22              6          88     87    True
10   20              3          72     68    True
11   25             10          96     98    True
12   21              5          84     80    True
13   23              7          91     90    True
14   19              1          55     45   False
15   22              6          87     84    True
16   24              8          94     92    True
17   20              4          76     70    True
18   21              5          82     79    True
19   23              7          89     88    True

## Correlation

Correlation measures the strength and direction of a linear relationship between two numerical variables.

Its value is between -1 and +1:

- +1  -> strong positive linear relationship
-  0  -> little/no linear relationship
- -1  -> strong negative linear relationship

In [26]:
df["hours_studied"].corr(df["score"])

np.float64(0.9613138435507224)

In [27]:
# correlation matrix for all numerical columns.
df.corr(numeric_only=True)

                    age  hours_studied  attendance     score    passed
age            1.000000       0.949211    0.849376  0.885187  0.589563
hours_studied  0.949211       1.000000    0.943732  0.961314  0.654601
attendance     0.849376       0.943732    1.000000  0.993733  0.775894
score          0.885187       0.961314    0.993733  1.000000  0.780192
passed         0.589563       0.654601    0.775894  0.780192  1.000000

## Separating Features and Target

One of the most common steps in an ML workflow is separating the input features from the target.

By convention:

- X → features
- y → target

In [28]:
X = df[["age", "hours_studied", "attendance"]]
y = df["score"]
print("X:\n", X)
print("\nX shape:", X.shape)
print("y shape:", y.shape)

X:
     age  hours_studied  attendance
0    20              3          70
1    21              5          85
2    19              2          65
3    22              7          95
4    20              6          90
5    23              8          98
6    21              4          78
7    19              2          60
8    24              9          92
9    22              6          88
10   20              3          72
11   25             10          96
12   21              5          84
13   23              7          91
14   19              1          55
15   22              6          87
16   24              8          94
17   20              4          76
18   21              5          82
19   23              7          89

X shape: (20, 3)
y shape: (20,)

## Converting Pandas Data to NumPy

Many ML libraries can work directly with Pandas, but converting to NumPy is sometimes useful. for this matter we use to_numpy().

In [29]:
X_array = X.to_numpy()
y_array = y.to_numpy()

print(type(X_array))
print(type(y_array))

print("\nX_array:")
print(X_array)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

X_array:
[[20  3 70]
 [21  5 85]
 [19  2 65]
 [22  7 95]
 [20  6 90]
 [23  8 98]
 [21  4 78]
 [19  2 60]
 [24  9 92]
 [22  6 88]
 [20  3 72]
 [25 10 96]
 [21  5 84]
 [23  7 91]
 [19  1 55]
 [22  6 87]
 [24  8 94]
 [20  4 76]
 [21  5 82]
 [23  7 89]]